name: Tests

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-backend-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: cr.selcloud.ru/mj-registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: |
          docker build -t api:2025 --target=api:2025 --build-arg user=martin --build-arg uid=1000 -f ./api/Dockerfile .
          docker tag api:2025 cr.selcloud.ru/mj-registry/api:2025
      - name: Push images
        run: |
          docker push cr.selcloud.ru/mj-registry/api:2025
