name: Tests

on:
  workflow_dispatch:
    branches: [ main ]
#  push:
#    branches: [ "main" ]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-backend-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: cr.selcloud.ru/mj-registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: |
          docker build -t api:3.0 --target=api --build-arg user=martin --build-arg uid=1000 -f ./api/Dockerfile .
          docker tag api:3.0 cr.selcloud.ru/mj-registry/api:3.0
      - name: Push images
        run: |
          docker push cr.selcloud.ru/mj-registry/api:3.0
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [ "build-backend-images" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          chmod +x kubectl
          mv ./kubectl /usr/local/bin
          kubectl version --output=yaml
          echo "${{ secrets.KUBE_CONFIG }}" | > $HOME/.kube/config
          kubectl get pods
